- name: Test Run Uvicorn Server
      env:
        ZF_SECRET: "d9c7e2b8fa4103d65b1e94a8c2f703496e51d8b2a0c7e3f495b6a7d8c9e0f1a2"
      run: |
        cd "${{ github.workspace }}"
        $job = Start-Job -ScriptBlock { uvicorn main:app --port 8000 }
        Start-Sleep -Seconds 10
        Stop-Job $job