name: Run Setup and Test Server

on:
  push:
    branches: [ main ]

jobs:
  run-project:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Match your Python version

    - name: Execute batch file
      run: |
        .\setup_venzv.bat

    - name: Test Run Uvicorn Server
      run: |
        # This starts the server in the background and kills it after 10 seconds to pass the test
        $job = Start-Job -ScriptBlock { uvicorn main:app --port 8000 }
        Start-Sleep -Seconds 10
        Stop-Job $job
