name: Run Setup and Test Server

on:
  push:
    branches: [ main ]

jobs:
  run-project:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Fixed: Uses the absolute workspace path to find the file perfectly
    - name: Copy .env.example to .env
      run: |
        Copy-Item "${{ github.workspace }}\.env.example" "${{ github.workspace }}\.env"

    - name: Execute batch file
      run: |
        cd "${{ github.workspace }}"
        .\setup_venzv.bat

    - name: Test Run Uvicorn Server
      env:
        ZF_SECRET: "github_actions_dummy_test_key_12345"
      run: |
        cd "${{ github.workspace }}"
        $job = Start-Job -ScriptBlock { uvicorn main:app --port 8000 }
        Start-Sleep -Seconds 10
        Stop-Job $job